baseURL = "http://raoufro.github.io/"
languageCode = "en-us"
languageName = "English"
title = "Raouf's website"
theme = "LoveIt"

# default amount of posts in each pages
paginate = 12
# google analytics code [UA-XXXXXXXX-X]
googleAnalytics = ""
# copyright description used only for seo schema
copyright = ""

# whether to use robots.txt
enableRobotsTXT = true
# whether to use git commit log
# enableGitInfo = true
# whether to use emoji code
enableEmoji = true

# Author config
[author]
  name = "Raouf RJ"
  #email = ""
  #link = ""


# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Posts"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = "Tags"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "Categories"

[params]
	# site default theme ["auto", "light", "dark"]
	defaultTheme = "dark"
	# public git repo url only then enableGitInfo is true
	# gitRepo = ""
	# LoveIt NEW | 0.1.1 which hash function used for SRI, when empty, no SRI is used
	# ["sha256", "sha384", "sha512", "md5"]
	# fingerprint = ""
	# LoveIt NEW | 0.2.0 date format
	dateFormat = "2006-01-02"
	# website title for Open Graph and Twitter Cards
	title = "RJ's Blog"
	# website description for RSS, SEO, Open Graph and Twitter Cards
	description = "RJ's Blog"
	# website images for Open Graph and Twitter Cards
	images = ["/logo.png"]

    # Header config
    [params.header]
    # desktop header mode ["fixed", "normal", "auto"]
    desktopMode = "fixed"
    # mobile header mode ["fixed", "normal", "auto"]
    mobileMode = "auto"
    # LoveIt NEW | 0.2.0 Header title config
    [params.header.title]
    # URL of the LOGO
    logo = ""
    # title name
    name = "RJ's Blog"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    #LoveIt NEW | 0.2.5 whether to use typeit animation for title name
    typeit = false
        
    # Footer config
    [params.footer]
    enable = true
    # LoveIt NEW | 0.2.0 Custom content (HTML format is supported)
    custom = ''
    # LoveIt NEW | 0.2.0 whether to show Hugo and theme info
    hugo = false
    # LoveIt NEW | 0.2.0 whether to show copyright info
    copyright = true
    # LoveIt NEW | 0.2.0 whether to show the author
    author = true
    # Site creation time
    since = 2023
    # license info (HTML format is supported)
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    
    # LoveIt NEW | 0.2.0 Section (all posts) page config
	[params.section]
    # special amount of posts in each section page
    paginate = 20
    # date format (month and day)
    dateFormat = "01-02"
    # amount of RSS pages
    rss = 10	

	# Home page config
	[params.home]
    # LoveIt NEW | 0.2.0 amount of RSS pages
    rss = 10
    # Home page profile
		[params.home.profile]
      	enable = true
      	# Gravatar Email for preferred avatar in home page
      	gravatarEmail = ""
      	# URL of avatar shown in home page
      	avatarURL = "/images/9aadeb3ce5957718cbdbe04ee481a935c88cf3697ee665fb3925689c7e6e2b2b_.png"
      	# LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
      	title = "Welcome to my blog!"
      	# subtitle shown in home page (HTML format is supported)
      	subtitle = "Hi! I'm Raouf. <br> I am enthusiastic about cybersecurity and system software.<br> I think I have good practical experience and theoretical knowledge of programming, SDLC, system software, and security, so I hope to share them with you here."
      	# whether to use typeit animation for subtitle
      	typeit = false
      	# whether to show social links
      	social = true
      	# LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
      	disclaimer = ""
    	# Home page posts
    	[params.home.posts]
      	enable = false
      	# special amount of posts in each home posts page
      	paginate = 6
      	# LoveIt DELETED | 0.2.0 replaced with hiddenFromHomePage in params.page
      	# default behavior when you don't set "hiddenFromHomePage" in front matter
      	defaultHiddenFromHomePage = false

	# Social config about the author
  	[params.social]
    	GitHub = "raoufro"
    	Linkedin = "raouf-rokhjavan"

	[params.page.share]
		enable = false

# Markup related configuration in Hugo
[markup]
	# Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
	[markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

